name: bionic_test_slicing
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  fl_chart: ^0.66.2
  video_player: ^2.8.2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/w100/Poppins-w100.ttf
          weight: 100
        - asset: fonts/poppins/w200/Poppins-w200.ttf
          weight: 200
        - asset: fonts/poppins/w300/Poppins-w300.ttf
          weight: 300
        - asset: fonts/poppins/w400/Poppins-w400.ttf
          weight: 400
        - asset: fonts/poppins/w500/Poppins-w500.ttf
          weight: 500
        - asset: fonts/poppins/w600/Poppins-w600.ttf
          weight: 600
        - asset: fonts/poppins/w700/Poppins-w700.ttf
          weight: 700
        - asset: fonts/poppins/w800/Poppins-w800.ttf
          weight: 800
